// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openconfig/hercules/proto/openconfig/openconfig_lacp/openconfig_lacp.proto

package openconfig_openconfig_lacp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import enums "github.com/openconfig/hercules/proto/openconfig/enums"
import _ "github.com/openconfig/ygot/proto/yext"
import ywrapper "github.com/openconfig/ygot/proto/ywrapper"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Lacp struct {
	Config               *Lacp_Config     `protobuf:"bytes,416417031,opt,name=config" json:"config,omitempty"`
	Interfaces           *Lacp_Interfaces `protobuf:"bytes,278182533,opt,name=interfaces" json:"interfaces,omitempty"`
	State                *Lacp_State      `protobuf:"bytes,340469368,opt,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Lacp) Reset()         { *m = Lacp{} }
func (m *Lacp) String() string { return proto.CompactTextString(m) }
func (*Lacp) ProtoMessage()    {}
func (*Lacp) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0}
}
func (m *Lacp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp.Unmarshal(m, b)
}
func (m *Lacp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp.Marshal(b, m, deterministic)
}
func (dst *Lacp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp.Merge(dst, src)
}
func (m *Lacp) XXX_Size() int {
	return xxx_messageInfo_Lacp.Size(m)
}
func (m *Lacp) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp proto.InternalMessageInfo

func (m *Lacp) GetConfig() *Lacp_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Lacp) GetInterfaces() *Lacp_Interfaces {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *Lacp) GetState() *Lacp_State {
	if m != nil {
		return m.State
	}
	return nil
}

type Lacp_Config struct {
	SystemPriority       *ywrapper.UintValue `protobuf:"bytes,71542334,opt,name=system_priority,json=systemPriority" json:"system_priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Lacp_Config) Reset()         { *m = Lacp_Config{} }
func (m *Lacp_Config) String() string { return proto.CompactTextString(m) }
func (*Lacp_Config) ProtoMessage()    {}
func (*Lacp_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 0}
}
func (m *Lacp_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Config.Unmarshal(m, b)
}
func (m *Lacp_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Config.Marshal(b, m, deterministic)
}
func (dst *Lacp_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Config.Merge(dst, src)
}
func (m *Lacp_Config) XXX_Size() int {
	return xxx_messageInfo_Lacp_Config.Size(m)
}
func (m *Lacp_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Config proto.InternalMessageInfo

func (m *Lacp_Config) GetSystemPriority() *ywrapper.UintValue {
	if m != nil {
		return m.SystemPriority
	}
	return nil
}

type Lacp_Interfaces struct {
	Interface            []*Lacp_Interfaces_InterfaceKey `protobuf:"bytes,212110241,rep,name=interface" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Lacp_Interfaces) Reset()         { *m = Lacp_Interfaces{} }
func (m *Lacp_Interfaces) String() string { return proto.CompactTextString(m) }
func (*Lacp_Interfaces) ProtoMessage()    {}
func (*Lacp_Interfaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 1}
}
func (m *Lacp_Interfaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Interfaces.Unmarshal(m, b)
}
func (m *Lacp_Interfaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Interfaces.Marshal(b, m, deterministic)
}
func (dst *Lacp_Interfaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Interfaces.Merge(dst, src)
}
func (m *Lacp_Interfaces) XXX_Size() int {
	return xxx_messageInfo_Lacp_Interfaces.Size(m)
}
func (m *Lacp_Interfaces) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Interfaces.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Interfaces proto.InternalMessageInfo

func (m *Lacp_Interfaces) GetInterface() []*Lacp_Interfaces_InterfaceKey {
	if m != nil {
		return m.Interface
	}
	return nil
}

type Lacp_Interfaces_Interface struct {
	Config               *Lacp_Interfaces_Interface_Config  `protobuf:"bytes,267814,opt,name=config" json:"config,omitempty"`
	Members              *Lacp_Interfaces_Interface_Members `protobuf:"bytes,448219541,opt,name=members" json:"members,omitempty"`
	State                *Lacp_Interfaces_Interface_State   `protobuf:"bytes,409381779,opt,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *Lacp_Interfaces_Interface) Reset()         { *m = Lacp_Interfaces_Interface{} }
func (m *Lacp_Interfaces_Interface) String() string { return proto.CompactTextString(m) }
func (*Lacp_Interfaces_Interface) ProtoMessage()    {}
func (*Lacp_Interfaces_Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 1, 0}
}
func (m *Lacp_Interfaces_Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Interfaces_Interface.Unmarshal(m, b)
}
func (m *Lacp_Interfaces_Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Interfaces_Interface.Marshal(b, m, deterministic)
}
func (dst *Lacp_Interfaces_Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Interfaces_Interface.Merge(dst, src)
}
func (m *Lacp_Interfaces_Interface) XXX_Size() int {
	return xxx_messageInfo_Lacp_Interfaces_Interface.Size(m)
}
func (m *Lacp_Interfaces_Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Interfaces_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Interfaces_Interface proto.InternalMessageInfo

func (m *Lacp_Interfaces_Interface) GetConfig() *Lacp_Interfaces_Interface_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Lacp_Interfaces_Interface) GetMembers() *Lacp_Interfaces_Interface_Members {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Lacp_Interfaces_Interface) GetState() *Lacp_Interfaces_Interface_State {
	if m != nil {
		return m.State
	}
	return nil
}

type Lacp_Interfaces_Interface_Config struct {
	Interval             enums.OpenconfigLacpLacpPeriodType   `protobuf:"varint,463085042,opt,name=interval,enum=openconfig.enums.OpenconfigLacpLacpPeriodType" json:"interval,omitempty"`
	LacpMode             enums.OpenconfigLacpLacpActivityType `protobuf:"varint,43173203,opt,name=lacp_mode,json=lacpMode,enum=openconfig.enums.OpenconfigLacpLacpActivityType" json:"lacp_mode,omitempty"`
	Name                 *ywrapper.StringValue                `protobuf:"bytes,73148204,opt,name=name" json:"name,omitempty"`
	SystemIdMac          *ywrapper.StringValue                `protobuf:"bytes,461403306,opt,name=system_id_mac,json=systemIdMac" json:"system_id_mac,omitempty"`
	SystemPriority       *ywrapper.UintValue                  `protobuf:"bytes,131529879,opt,name=system_priority,json=systemPriority" json:"system_priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Lacp_Interfaces_Interface_Config) Reset()         { *m = Lacp_Interfaces_Interface_Config{} }
func (m *Lacp_Interfaces_Interface_Config) String() string { return proto.CompactTextString(m) }
func (*Lacp_Interfaces_Interface_Config) ProtoMessage()    {}
func (*Lacp_Interfaces_Interface_Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 1, 0, 0}
}
func (m *Lacp_Interfaces_Interface_Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Config.Unmarshal(m, b)
}
func (m *Lacp_Interfaces_Interface_Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Config.Marshal(b, m, deterministic)
}
func (dst *Lacp_Interfaces_Interface_Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Interfaces_Interface_Config.Merge(dst, src)
}
func (m *Lacp_Interfaces_Interface_Config) XXX_Size() int {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Config.Size(m)
}
func (m *Lacp_Interfaces_Interface_Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Interfaces_Interface_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Interfaces_Interface_Config proto.InternalMessageInfo

func (m *Lacp_Interfaces_Interface_Config) GetInterval() enums.OpenconfigLacpLacpPeriodType {
	if m != nil {
		return m.Interval
	}
	return enums.OpenconfigLacpLacpPeriodType_OPENCONFIGLACPLACPPERIODTYPE_SLOW
}

func (m *Lacp_Interfaces_Interface_Config) GetLacpMode() enums.OpenconfigLacpLacpActivityType {
	if m != nil {
		return m.LacpMode
	}
	return enums.OpenconfigLacpLacpActivityType_OPENCONFIGLACPLACPACTIVITYTYPE_ACTIVE
}

func (m *Lacp_Interfaces_Interface_Config) GetName() *ywrapper.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Config) GetSystemIdMac() *ywrapper.StringValue {
	if m != nil {
		return m.SystemIdMac
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Config) GetSystemPriority() *ywrapper.UintValue {
	if m != nil {
		return m.SystemPriority
	}
	return nil
}

type Lacp_Interfaces_Interface_Members struct {
	Member               []*Lacp_Interfaces_Interface_Members_MemberKey `protobuf:"bytes,107372070,rep,name=member" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *Lacp_Interfaces_Interface_Members) Reset()         { *m = Lacp_Interfaces_Interface_Members{} }
func (m *Lacp_Interfaces_Interface_Members) String() string { return proto.CompactTextString(m) }
func (*Lacp_Interfaces_Interface_Members) ProtoMessage()    {}
func (*Lacp_Interfaces_Interface_Members) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 1, 0, 1}
}
func (m *Lacp_Interfaces_Interface_Members) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members.Unmarshal(m, b)
}
func (m *Lacp_Interfaces_Interface_Members) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members.Marshal(b, m, deterministic)
}
func (dst *Lacp_Interfaces_Interface_Members) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Interfaces_Interface_Members.Merge(dst, src)
}
func (m *Lacp_Interfaces_Interface_Members) XXX_Size() int {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members.Size(m)
}
func (m *Lacp_Interfaces_Interface_Members) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Interfaces_Interface_Members.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Interfaces_Interface_Members proto.InternalMessageInfo

func (m *Lacp_Interfaces_Interface_Members) GetMember() []*Lacp_Interfaces_Interface_Members_MemberKey {
	if m != nil {
		return m.Member
	}
	return nil
}

type Lacp_Interfaces_Interface_Members_Member struct {
	State                *Lacp_Interfaces_Interface_Members_Member_State `protobuf:"bytes,101613208,opt,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *Lacp_Interfaces_Interface_Members_Member) Reset() {
	*m = Lacp_Interfaces_Interface_Members_Member{}
}
func (m *Lacp_Interfaces_Interface_Members_Member) String() string { return proto.CompactTextString(m) }
func (*Lacp_Interfaces_Interface_Members_Member) ProtoMessage()    {}
func (*Lacp_Interfaces_Interface_Members_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 1, 0, 1, 0}
}
func (m *Lacp_Interfaces_Interface_Members_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member.Unmarshal(m, b)
}
func (m *Lacp_Interfaces_Interface_Members_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member.Marshal(b, m, deterministic)
}
func (dst *Lacp_Interfaces_Interface_Members_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member.Merge(dst, src)
}
func (m *Lacp_Interfaces_Interface_Members_Member) XXX_Size() int {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member.Size(m)
}
func (m *Lacp_Interfaces_Interface_Members_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member proto.InternalMessageInfo

func (m *Lacp_Interfaces_Interface_Members_Member) GetState() *Lacp_Interfaces_Interface_Members_Member_State {
	if m != nil {
		return m.State
	}
	return nil
}

type Lacp_Interfaces_Interface_Members_Member_State struct {
	Activity             enums.OpenconfigLacpLacpActivityType                     `protobuf:"varint,344383748,opt,name=activity,enum=openconfig.enums.OpenconfigLacpLacpActivityType" json:"activity,omitempty"`
	Aggregatable         *ywrapper.BoolValue                                      `protobuf:"bytes,490059983,opt,name=aggregatable" json:"aggregatable,omitempty"`
	Collecting           *ywrapper.BoolValue                                      `protobuf:"bytes,431241365,opt,name=collecting" json:"collecting,omitempty"`
	Counters             *Lacp_Interfaces_Interface_Members_Member_State_Counters `protobuf:"bytes,159126128,opt,name=counters" json:"counters,omitempty"`
	Distributing         *ywrapper.BoolValue                                      `protobuf:"bytes,325869523,opt,name=distributing" json:"distributing,omitempty"`
	Interface            *ywrapper.StringValue                                    `protobuf:"bytes,140807600,opt,name=interface" json:"interface,omitempty"`
	OperKey              *ywrapper.UintValue                                      `protobuf:"bytes,503255861,opt,name=oper_key,json=operKey" json:"oper_key,omitempty"`
	PartnerId            *ywrapper.StringValue                                    `protobuf:"bytes,342233611,opt,name=partner_id,json=partnerId" json:"partner_id,omitempty"`
	PartnerKey           *ywrapper.UintValue                                      `protobuf:"bytes,313821353,opt,name=partner_key,json=partnerKey" json:"partner_key,omitempty"`
	PartnerPortNum       *ywrapper.UintValue                                      `protobuf:"bytes,11089282,opt,name=partner_port_num,json=partnerPortNum" json:"partner_port_num,omitempty"`
	PortNum              *ywrapper.UintValue                                      `protobuf:"bytes,55409541,opt,name=port_num,json=portNum" json:"port_num,omitempty"`
	Synchronization      enums.OpenconfigLacpLacpSynchronizationType              `protobuf:"varint,179070617,opt,name=synchronization,enum=openconfig.enums.OpenconfigLacpLacpSynchronizationType" json:"synchronization,omitempty"`
	SystemId             *ywrapper.StringValue                                    `protobuf:"bytes,207537082,opt,name=system_id,json=systemId" json:"system_id,omitempty"`
	Timeout              enums.OpenconfigLacpLacpTimeoutType                      `protobuf:"varint,834808,opt,name=timeout,enum=openconfig.enums.OpenconfigLacpLacpTimeoutType" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                 `json:"-"`
	XXX_unrecognized     []byte                                                   `json:"-"`
	XXX_sizecache        int32                                                    `json:"-"`
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) Reset() {
	*m = Lacp_Interfaces_Interface_Members_Member_State{}
}
func (m *Lacp_Interfaces_Interface_Members_Member_State) String() string {
	return proto.CompactTextString(m)
}
func (*Lacp_Interfaces_Interface_Members_Member_State) ProtoMessage() {}
func (*Lacp_Interfaces_Interface_Members_Member_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 1, 0, 1, 0, 0}
}
func (m *Lacp_Interfaces_Interface_Members_Member_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State.Unmarshal(m, b)
}
func (m *Lacp_Interfaces_Interface_Members_Member_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State.Marshal(b, m, deterministic)
}
func (dst *Lacp_Interfaces_Interface_Members_Member_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State.Merge(dst, src)
}
func (m *Lacp_Interfaces_Interface_Members_Member_State) XXX_Size() int {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State.Size(m)
}
func (m *Lacp_Interfaces_Interface_Members_Member_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State proto.InternalMessageInfo

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetActivity() enums.OpenconfigLacpLacpActivityType {
	if m != nil {
		return m.Activity
	}
	return enums.OpenconfigLacpLacpActivityType_OPENCONFIGLACPLACPACTIVITYTYPE_ACTIVE
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetAggregatable() *ywrapper.BoolValue {
	if m != nil {
		return m.Aggregatable
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetCollecting() *ywrapper.BoolValue {
	if m != nil {
		return m.Collecting
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetCounters() *Lacp_Interfaces_Interface_Members_Member_State_Counters {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetDistributing() *ywrapper.BoolValue {
	if m != nil {
		return m.Distributing
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetInterface() *ywrapper.StringValue {
	if m != nil {
		return m.Interface
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetOperKey() *ywrapper.UintValue {
	if m != nil {
		return m.OperKey
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetPartnerId() *ywrapper.StringValue {
	if m != nil {
		return m.PartnerId
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetPartnerKey() *ywrapper.UintValue {
	if m != nil {
		return m.PartnerKey
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetPartnerPortNum() *ywrapper.UintValue {
	if m != nil {
		return m.PartnerPortNum
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetPortNum() *ywrapper.UintValue {
	if m != nil {
		return m.PortNum
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetSynchronization() enums.OpenconfigLacpLacpSynchronizationType {
	if m != nil {
		return m.Synchronization
	}
	return enums.OpenconfigLacpLacpSynchronizationType_OPENCONFIGLACPLACPSYNCHRONIZATIONTYPE_UNSET
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetSystemId() *ywrapper.StringValue {
	if m != nil {
		return m.SystemId
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State) GetTimeout() enums.OpenconfigLacpLacpTimeoutType {
	if m != nil {
		return m.Timeout
	}
	return enums.OpenconfigLacpLacpTimeoutType_OPENCONFIGLACPLACPTIMEOUTTYPE_UNSET
}

type Lacp_Interfaces_Interface_Members_Member_State_Counters struct {
	LacpErrors           *ywrapper.UintValue `protobuf:"bytes,432819317,opt,name=lacp_errors,json=lacpErrors" json:"lacp_errors,omitempty"`
	LacpInPkts           *ywrapper.UintValue `protobuf:"bytes,133444718,opt,name=lacp_in_pkts,json=lacpInPkts" json:"lacp_in_pkts,omitempty"`
	LacpOutPkts          *ywrapper.UintValue `protobuf:"bytes,391388365,opt,name=lacp_out_pkts,json=lacpOutPkts" json:"lacp_out_pkts,omitempty"`
	LacpRxErrors         *ywrapper.UintValue `protobuf:"bytes,124474434,opt,name=lacp_rx_errors,json=lacpRxErrors" json:"lacp_rx_errors,omitempty"`
	LacpTxErrors         *ywrapper.UintValue `protobuf:"bytes,98014728,opt,name=lacp_tx_errors,json=lacpTxErrors" json:"lacp_tx_errors,omitempty"`
	LacpUnknownErrors    *ywrapper.UintValue `protobuf:"bytes,33984050,opt,name=lacp_unknown_errors,json=lacpUnknownErrors" json:"lacp_unknown_errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) Reset() {
	*m = Lacp_Interfaces_Interface_Members_Member_State_Counters{}
}
func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) String() string {
	return proto.CompactTextString(m)
}
func (*Lacp_Interfaces_Interface_Members_Member_State_Counters) ProtoMessage() {}
func (*Lacp_Interfaces_Interface_Members_Member_State_Counters) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 1, 0, 1, 0, 0, 0}
}
func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State_Counters.Unmarshal(m, b)
}
func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State_Counters.Marshal(b, m, deterministic)
}
func (dst *Lacp_Interfaces_Interface_Members_Member_State_Counters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State_Counters.Merge(dst, src)
}
func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) XXX_Size() int {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State_Counters.Size(m)
}
func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State_Counters.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Interfaces_Interface_Members_Member_State_Counters proto.InternalMessageInfo

func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) GetLacpErrors() *ywrapper.UintValue {
	if m != nil {
		return m.LacpErrors
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) GetLacpInPkts() *ywrapper.UintValue {
	if m != nil {
		return m.LacpInPkts
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) GetLacpOutPkts() *ywrapper.UintValue {
	if m != nil {
		return m.LacpOutPkts
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) GetLacpRxErrors() *ywrapper.UintValue {
	if m != nil {
		return m.LacpRxErrors
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) GetLacpTxErrors() *ywrapper.UintValue {
	if m != nil {
		return m.LacpTxErrors
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_Members_Member_State_Counters) GetLacpUnknownErrors() *ywrapper.UintValue {
	if m != nil {
		return m.LacpUnknownErrors
	}
	return nil
}

type Lacp_Interfaces_Interface_Members_MemberKey struct {
	Interface            string                                    `protobuf:"bytes,1,opt,name=interface" json:"interface,omitempty"`
	Member               *Lacp_Interfaces_Interface_Members_Member `protobuf:"bytes,2,opt,name=member" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *Lacp_Interfaces_Interface_Members_MemberKey) Reset() {
	*m = Lacp_Interfaces_Interface_Members_MemberKey{}
}
func (m *Lacp_Interfaces_Interface_Members_MemberKey) String() string {
	return proto.CompactTextString(m)
}
func (*Lacp_Interfaces_Interface_Members_MemberKey) ProtoMessage() {}
func (*Lacp_Interfaces_Interface_Members_MemberKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 1, 0, 1, 1}
}
func (m *Lacp_Interfaces_Interface_Members_MemberKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_MemberKey.Unmarshal(m, b)
}
func (m *Lacp_Interfaces_Interface_Members_MemberKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_MemberKey.Marshal(b, m, deterministic)
}
func (dst *Lacp_Interfaces_Interface_Members_MemberKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Interfaces_Interface_Members_MemberKey.Merge(dst, src)
}
func (m *Lacp_Interfaces_Interface_Members_MemberKey) XXX_Size() int {
	return xxx_messageInfo_Lacp_Interfaces_Interface_Members_MemberKey.Size(m)
}
func (m *Lacp_Interfaces_Interface_Members_MemberKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Interfaces_Interface_Members_MemberKey.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Interfaces_Interface_Members_MemberKey proto.InternalMessageInfo

func (m *Lacp_Interfaces_Interface_Members_MemberKey) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *Lacp_Interfaces_Interface_Members_MemberKey) GetMember() *Lacp_Interfaces_Interface_Members_Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type Lacp_Interfaces_Interface_State struct {
	Interval             enums.OpenconfigLacpLacpPeriodType   `protobuf:"varint,156781677,opt,name=interval,enum=openconfig.enums.OpenconfigLacpLacpPeriodType" json:"interval,omitempty"`
	LacpMode             enums.OpenconfigLacpLacpActivityType `protobuf:"varint,285910318,opt,name=lacp_mode,json=lacpMode,enum=openconfig.enums.OpenconfigLacpLacpActivityType" json:"lacp_mode,omitempty"`
	Name                 *ywrapper.StringValue                `protobuf:"bytes,53396163,opt,name=name" json:"name,omitempty"`
	SystemIdMac          *ywrapper.StringValue                `protobuf:"bytes,308184979,opt,name=system_id_mac,json=systemIdMac" json:"system_id_mac,omitempty"`
	SystemPriority       *ywrapper.UintValue                  `protobuf:"bytes,386600370,opt,name=system_priority,json=systemPriority" json:"system_priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Lacp_Interfaces_Interface_State) Reset()         { *m = Lacp_Interfaces_Interface_State{} }
func (m *Lacp_Interfaces_Interface_State) String() string { return proto.CompactTextString(m) }
func (*Lacp_Interfaces_Interface_State) ProtoMessage()    {}
func (*Lacp_Interfaces_Interface_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 1, 0, 2}
}
func (m *Lacp_Interfaces_Interface_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Interfaces_Interface_State.Unmarshal(m, b)
}
func (m *Lacp_Interfaces_Interface_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Interfaces_Interface_State.Marshal(b, m, deterministic)
}
func (dst *Lacp_Interfaces_Interface_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Interfaces_Interface_State.Merge(dst, src)
}
func (m *Lacp_Interfaces_Interface_State) XXX_Size() int {
	return xxx_messageInfo_Lacp_Interfaces_Interface_State.Size(m)
}
func (m *Lacp_Interfaces_Interface_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Interfaces_Interface_State.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Interfaces_Interface_State proto.InternalMessageInfo

func (m *Lacp_Interfaces_Interface_State) GetInterval() enums.OpenconfigLacpLacpPeriodType {
	if m != nil {
		return m.Interval
	}
	return enums.OpenconfigLacpLacpPeriodType_OPENCONFIGLACPLACPPERIODTYPE_SLOW
}

func (m *Lacp_Interfaces_Interface_State) GetLacpMode() enums.OpenconfigLacpLacpActivityType {
	if m != nil {
		return m.LacpMode
	}
	return enums.OpenconfigLacpLacpActivityType_OPENCONFIGLACPLACPACTIVITYTYPE_ACTIVE
}

func (m *Lacp_Interfaces_Interface_State) GetName() *ywrapper.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_State) GetSystemIdMac() *ywrapper.StringValue {
	if m != nil {
		return m.SystemIdMac
	}
	return nil
}

func (m *Lacp_Interfaces_Interface_State) GetSystemPriority() *ywrapper.UintValue {
	if m != nil {
		return m.SystemPriority
	}
	return nil
}

type Lacp_Interfaces_InterfaceKey struct {
	Name                 string                     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Interface            *Lacp_Interfaces_Interface `protobuf:"bytes,2,opt,name=interface" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Lacp_Interfaces_InterfaceKey) Reset()         { *m = Lacp_Interfaces_InterfaceKey{} }
func (m *Lacp_Interfaces_InterfaceKey) String() string { return proto.CompactTextString(m) }
func (*Lacp_Interfaces_InterfaceKey) ProtoMessage()    {}
func (*Lacp_Interfaces_InterfaceKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 1, 1}
}
func (m *Lacp_Interfaces_InterfaceKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_Interfaces_InterfaceKey.Unmarshal(m, b)
}
func (m *Lacp_Interfaces_InterfaceKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_Interfaces_InterfaceKey.Marshal(b, m, deterministic)
}
func (dst *Lacp_Interfaces_InterfaceKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_Interfaces_InterfaceKey.Merge(dst, src)
}
func (m *Lacp_Interfaces_InterfaceKey) XXX_Size() int {
	return xxx_messageInfo_Lacp_Interfaces_InterfaceKey.Size(m)
}
func (m *Lacp_Interfaces_InterfaceKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_Interfaces_InterfaceKey.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_Interfaces_InterfaceKey proto.InternalMessageInfo

func (m *Lacp_Interfaces_InterfaceKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lacp_Interfaces_InterfaceKey) GetInterface() *Lacp_Interfaces_Interface {
	if m != nil {
		return m.Interface
	}
	return nil
}

type Lacp_State struct {
	SystemPriority       *ywrapper.UintValue `protobuf:"bytes,509622121,opt,name=system_priority,json=systemPriority" json:"system_priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Lacp_State) Reset()         { *m = Lacp_State{} }
func (m *Lacp_State) String() string { return proto.CompactTextString(m) }
func (*Lacp_State) ProtoMessage()    {}
func (*Lacp_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_openconfig_lacp_9eb6054709a7a623, []int{0, 2}
}
func (m *Lacp_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lacp_State.Unmarshal(m, b)
}
func (m *Lacp_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lacp_State.Marshal(b, m, deterministic)
}
func (dst *Lacp_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lacp_State.Merge(dst, src)
}
func (m *Lacp_State) XXX_Size() int {
	return xxx_messageInfo_Lacp_State.Size(m)
}
func (m *Lacp_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Lacp_State.DiscardUnknown(m)
}

var xxx_messageInfo_Lacp_State proto.InternalMessageInfo

func (m *Lacp_State) GetSystemPriority() *ywrapper.UintValue {
	if m != nil {
		return m.SystemPriority
	}
	return nil
}

func init() {
	proto.RegisterType((*Lacp)(nil), "openconfig.openconfig_lacp.Lacp")
	proto.RegisterType((*Lacp_Config)(nil), "openconfig.openconfig_lacp.Lacp.Config")
	proto.RegisterType((*Lacp_Interfaces)(nil), "openconfig.openconfig_lacp.Lacp.Interfaces")
	proto.RegisterType((*Lacp_Interfaces_Interface)(nil), "openconfig.openconfig_lacp.Lacp.Interfaces.Interface")
	proto.RegisterType((*Lacp_Interfaces_Interface_Config)(nil), "openconfig.openconfig_lacp.Lacp.Interfaces.Interface.Config")
	proto.RegisterType((*Lacp_Interfaces_Interface_Members)(nil), "openconfig.openconfig_lacp.Lacp.Interfaces.Interface.Members")
	proto.RegisterType((*Lacp_Interfaces_Interface_Members_Member)(nil), "openconfig.openconfig_lacp.Lacp.Interfaces.Interface.Members.Member")
	proto.RegisterType((*Lacp_Interfaces_Interface_Members_Member_State)(nil), "openconfig.openconfig_lacp.Lacp.Interfaces.Interface.Members.Member.State")
	proto.RegisterType((*Lacp_Interfaces_Interface_Members_Member_State_Counters)(nil), "openconfig.openconfig_lacp.Lacp.Interfaces.Interface.Members.Member.State.Counters")
	proto.RegisterType((*Lacp_Interfaces_Interface_Members_MemberKey)(nil), "openconfig.openconfig_lacp.Lacp.Interfaces.Interface.Members.MemberKey")
	proto.RegisterType((*Lacp_Interfaces_Interface_State)(nil), "openconfig.openconfig_lacp.Lacp.Interfaces.Interface.State")
	proto.RegisterType((*Lacp_Interfaces_InterfaceKey)(nil), "openconfig.openconfig_lacp.Lacp.Interfaces.InterfaceKey")
	proto.RegisterType((*Lacp_State)(nil), "openconfig.openconfig_lacp.Lacp.State")
}

func init() {
	proto.RegisterFile("github.com/openconfig/hercules/proto/openconfig/openconfig_lacp/openconfig_lacp.proto", fileDescriptor_openconfig_lacp_9eb6054709a7a623)
}

var fileDescriptor_openconfig_lacp_9eb6054709a7a623 = []byte{
	// 1588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x6d, 0x6c, 0x14, 0xd5,
	0x1a, 0xce, 0xdc, 0x5b, 0xda, 0xed, 0x69, 0x29, 0xbd, 0x87, 0xcb, 0xcd, 0xb0, 0xf7, 0x03, 0x6e,
	0xef, 0xe5, 0x4b, 0xdc, 0xdd, 0xd2, 0x2a, 0x20, 0xe5, 0xc3, 0xb3, 0x05, 0xb1, 0x7c, 0x48, 0x33,
	0x6d, 0xf1, 0x8f, 0xc9, 0x3a, 0xdd, 0x3d, 0x2c, 0x63, 0x77, 0x67, 0xd6, 0xd9, 0x33, 0xd0, 0x45,
	0x4c, 0xe0, 0x84, 0x4a, 0x83, 0x11, 0x15, 0x42, 0x5a, 0xa8, 0x7f, 0xd4, 0x86, 0x20, 0x29, 0x2a,
	0x24, 0x18, 0x01, 0x23, 0x09, 0x24, 0x86, 0x08, 0x45, 0x02, 0x51, 0x7f, 0x08, 0x26, 0xfe, 0x83,
	0x18, 0x11, 0x34, 0x44, 0xf0, 0x23, 0x31, 0x73, 0xce, 0xcc, 0xec, 0x74, 0xed, 0xce, 0x76, 0xb7,
	0xf5, 0x47, 0x77, 0xce, 0x9c, 0xce, 0xfb, 0x3e, 0xcf, 0x79, 0xbf, 0xe6, 0x7d, 0x07, 0x74, 0xc4,
	0x15, 0xb2, 0xd9, 0xe8, 0x0c, 0x46, 0xb5, 0x64, 0x48, 0x4b, 0x61, 0x35, 0xaa, 0xa9, 0x9b, 0x94,
	0x78, 0x68, 0x33, 0xd6, 0xa3, 0x46, 0x02, 0xa7, 0x43, 0x29, 0x5d, 0x23, 0x9a, 0xfb, 0x3f, 0xd9,
	0x65, 0x24, 0x21, 0x47, 0x53, 0xb9, 0xf7, 0x41, 0x26, 0x00, 0xfd, 0xd9, 0xed, 0x60, 0xce, 0x13,
	0xfe, 0xc5, 0xa3, 0x43, 0x66, 0xe2, 0x1a, 0xb1, 0xe0, 0x32, 0x5b, 0x75, 0x39, 0x95, 0xc2, 0xba,
	0xb3, 0xe0, 0x5a, 0xfd, 0xf5, 0x85, 0x25, 0x71, 0x37, 0x61, 0x3f, 0x96, 0x04, 0x2a, 0xf6, 0x78,
	0x58, 0x35, 0x92, 0x69, 0xfe, 0xcb, 0x55, 0xd4, 0x5d, 0x9c, 0x0f, 0xca, 0xd6, 0xc9, 0xd1, 0x14,
	0x6c, 0x07, 0xe5, 0xfc, 0x21, 0x71, 0xf7, 0x9e, 0x0b, 0x9f, 0x08, 0x33, 0x85, 0xb9, 0x55, 0x0d,
	0x73, 0x82, 0xf9, 0x0f, 0x1a, 0x34, 0xa5, 0x82, 0xcd, 0x6c, 0x23, 0x3c, 0x85, 0xa2, 0xea, 0x10,
	0x33, 0x18, 0x7f, 0x42, 0xb2, 0x74, 0xc1, 0x18, 0x00, 0x8a, 0x4a, 0xb0, 0xbe, 0x49, 0x8e, 0xe2,
	0xb4, 0xd8, 0x73, 0xef, 0xea, 0x2e, 0xae, 0x79, 0x7e, 0x41, 0xcd, 0x2d, 0x8e, 0x58, 0x78, 0x2a,
	0x45, 0xb5, 0x5c, 0x7b, 0x56, 0x97, 0xe4, 0xd2, 0x0b, 0x5b, 0xc1, 0xa4, 0x34, 0x91, 0x09, 0x16,
	0xef, 0x5f, 0x1a, 0x7a, 0x8b, 0x03, 0xcc, 0x2e, 0x08, 0xd0, 0x66, 0x4a, 0x84, 0x6b, 0x28, 0xaa,
	0xe2, 0xba, 0x99, 0x06, 0x89, 0x2b, 0xf2, 0x3f, 0x07, 0xca, 0xf9, 0xd1, 0xe0, 0xb3, 0x60, 0x4a,
	0x3a, 0x93, 0x26, 0x38, 0x19, 0x49, 0xe9, 0x8a, 0xa6, 0x2b, 0x24, 0x23, 0x7e, 0x7c, 0x69, 0x6f,
	0x1d, 0x03, 0x99, 0x1a, 0x74, 0x5c, 0xd8, 0xa1, 0xa8, 0x64, 0xa3, 0x9c, 0x30, 0x70, 0x78, 0x06,
	0x45, 0xff, 0x72, 0xdb, 0x22, 0xc4, 0xc5, 0x03, 0xb6, 0xb8, 0x54, 0xc3, 0x37, 0x5a, 0xad, 0x7b,
	0xff, 0x8d, 0x39, 0x00, 0x64, 0x4f, 0x0b, 0xbb, 0x41, 0xa5, 0x73, 0x34, 0xf1, 0xcd, 0xbe, 0x7d,
	0x78, 0xe6, 0x5f, 0xe7, 0x56, 0x35, 0x2c, 0x2e, 0xc2, 0x60, 0xd9, 0xe5, 0x5a, 0x9c, 0x09, 0xff,
	0x9b, 0x22, 0x7f, 0xae, 0xf5, 0xb2, 0x4b, 0x29, 0x0b, 0xe6, 0xff, 0x60, 0x16, 0xa8, 0x74, 0x44,
	0xe1, 0x76, 0x27, 0x20, 0x0e, 0x0f, 0xd5, 0xb2, 0xe3, 0x2e, 0x2d, 0x89, 0x83, 0x1d, 0x23, 0xff,
	0xa7, 0xe8, 0xbf, 0xf9, 0x79, 0xe4, 0x06, 0x0e, 0x15, 0x40, 0x45, 0x12, 0x27, 0x3b, 0xb1, 0x9e,
	0x16, 0x0f, 0xec, 0xbf, 0xf1, 0x39, 0xf7, 0xea, 0xb2, 0xd2, 0x18, 0xac, 0xe7, 0x8a, 0xc2, 0xb3,
	0x28, 0xaa, 0xf3, 0xa0, 0x60, 0xe1, 0x49, 0x36, 0x30, 0xdc, 0x66, 0xc7, 0xd5, 0xfe, 0x2f, 0x0f,
	0x9d, 0xe7, 0x0c, 0x9a, 0x4a, 0x63, 0xc0, 0x83, 0xed, 0x7f, 0x14, 0xcd, 0xf4, 0xc0, 0x1f, 0x11,
	0x81, 0xc3, 0x65, 0x4e, 0x08, 0xbe, 0x08, 0x7c, 0xec, 0xa1, 0x2d, 0x72, 0x42, 0xfc, 0xe1, 0xcc,
	0xcd, 0xeb, 0x26, 0x93, 0x9a, 0x86, 0xa0, 0x9b, 0x09, 0x4f, 0xe9, 0x0d, 0xce, 0x86, 0xc9, 0xc4,
	0xfc, 0x6b, 0xc5, 0xba, 0xa2, 0xc5, 0xda, 0x33, 0x29, 0x1c, 0x0e, 0x50, 0xf4, 0x50, 0x41, 0xfb,
	0x87, 0x6c, 0x20, 0xc9, 0x81, 0x84, 0x3b, 0x04, 0x50, 0x69, 0xca, 0x45, 0x92, 0x5a, 0x0c, 0x8b,
	0xd7, 0xf6, 0x5c, 0xfc, 0x3b, 0xc3, 0xaf, 0x1f, 0x0b, 0x3e, 0x8a, 0x12, 0x65, 0x8b, 0x42, 0x32,
	0x8c, 0x41, 0x90, 0xa2, 0xf9, 0x85, 0x19, 0x98, 0x0f, 0x04, 0x4c, 0x28, 0xc9, 0x67, 0x2e, 0xd7,
	0x6b, 0x31, 0x0c, 0x9f, 0x06, 0x65, 0xaa, 0x9c, 0xc4, 0xe2, 0xd0, 0xe5, 0x3b, 0x3c, 0xf3, 0xa6,
	0x65, 0x33, 0xaf, 0x8d, 0xe8, 0x8a, 0x1a, 0xe7, 0xb9, 0x37, 0x8f, 0xa2, 0xd9, 0x85, 0x11, 0x4c,
	0x55, 0x12, 0x53, 0x08, 0x9f, 0x07, 0x93, 0xad, 0xec, 0x56, 0x62, 0x91, 0xa4, 0x1c, 0x15, 0x8f,
	0xde, 0xda, 0x79, 0x5d, 0xf0, 0x82, 0x68, 0xa0, 0x28, 0x54, 0x18, 0xc2, 0xca, 0x79, 0x25, 0x16,
	0x48, 0xca, 0x51, 0xa9, 0x8a, 0xdf, 0xb6, 0xc4, 0xd6, 0xcb, 0x51, 0x68, 0xfc, 0xb1, 0xa0, 0xf4,
	0x3d, 0xf8, 0x6a, 0x79, 0xfe, 0x82, 0xf2, 0x08, 0x45, 0x0b, 0xc6, 0x8c, 0x98, 0xb7, 0xca, 0xec,
	0x9d, 0x0e, 0x2a, 0xac, 0x3c, 0x80, 0xaf, 0x09, 0xa0, 0x9c, 0xc7, 0xb8, 0x78, 0xf8, 0xa3, 0x83,
	0x8d, 0xac, 0xc0, 0xac, 0x1e, 0x57, 0x6a, 0x59, 0x57, 0xb3, 0xde, 0x3c, 0x4c, 0xd1, 0xbc, 0xc2,
	0x49, 0x66, 0x5d, 0x25, 0x8b, 0x87, 0xff, 0xd8, 0x3f, 0x40, 0x39, 0xd7, 0x01, 0xfb, 0x04, 0x3b,
	0xed, 0xfa, 0x7f, 0x3b, 0x55, 0xcf, 0xec, 0xb2, 0x66, 0x22, 0xc8, 0x59, 0x49, 0x58, 0xc0, 0x81,
	0x23, 0xf9, 0x8d, 0xcc, 0xc9, 0xde, 0x69, 0x60, 0x12, 0x53, 0x02, 0x5f, 0x11, 0x80, 0x4f, 0xb6,
	0x62, 0x5b, 0xdc, 0x75, 0x6e, 0x60, 0x50, 0x28, 0x31, 0x27, 0x9a, 0x28, 0x5a, 0x5c, 0x24, 0x9b,
	0x90, 0x0d, 0x2c, 0x39, 0x14, 0xe0, 0x76, 0x50, 0x2d, 0xc7, 0xe3, 0x3a, 0x8e, 0xcb, 0x44, 0xee,
	0x4c, 0x60, 0xf1, 0xb3, 0xbb, 0x5f, 0xdc, 0x12, 0x72, 0x43, 0x2a, 0xac, 0x69, 0x09, 0x1e, 0x52,
	0x2b, 0x28, 0x5a, 0x5a, 0x34, 0xaa, 0x4b, 0xbf, 0x34, 0x02, 0x0d, 0x6e, 0x01, 0x20, 0xaa, 0x25,
	0x12, 0x38, 0x4a, 0x14, 0x35, 0x2e, 0x1e, 0xb8, 0x7b, 0x65, 0xd8, 0x03, 0x7b, 0x19, 0x45, 0x4b,
	0x8a, 0xc5, 0xce, 0x6a, 0x97, 0x5c, 0x48, 0xf0, 0x3d, 0x01, 0xf8, 0xa2, 0x9a, 0x61, 0xca, 0xa6,
	0xc5, 0x3b, 0x83, 0x77, 0xd6, 0x32, 0xd4, 0xb6, 0x89, 0x0b, 0x96, 0x60, 0xb3, 0xa5, 0xbd, 0x24,
	0x3f, 0xd9, 0xd4, 0x24, 0x87, 0xa4, 0xe9, 0xa7, 0x98, 0x92, 0x26, 0xba, 0xd2, 0x69, 0x30, 0x5b,
	0x5d, 0x3b, 0x7b, 0x7c, 0x60, 0x82, 0xfd, 0xe4, 0xd6, 0x2f, 0x8d, 0x40, 0x83, 0xc4, 0xdd, 0x5a,
	0xbc, 0x3f, 0xb0, 0xaf, 0xd9, 0xab, 0xd0, 0x2d, 0xa5, 0xe8, 0xb1, 0x62, 0xb1, 0x47, 0x6b, 0x2b,
	0xa0, 0x06, 0x7c, 0x5a, 0x0a, 0xeb, 0x91, 0x2e, 0x9c, 0x11, 0x4f, 0x1e, 0xfe, 0xf5, 0x7b, 0x21,
	0x7f, 0xa9, 0x2b, 0xc5, 0xca, 0xa6, 0xee, 0x40, 0x17, 0xce, 0x48, 0x15, 0xe6, 0x6a, 0x2d, 0xce,
	0xc0, 0xad, 0x00, 0xa4, 0x64, 0x9d, 0xa8, 0x58, 0x8f, 0x28, 0x31, 0xf1, 0xe5, 0xc1, 0xfe, 0xb7,
	0x3d, 0x2b, 0x7a, 0x29, 0x01, 0x69, 0xe9, 0x0f, 0x28, 0x31, 0xa9, 0xd2, 0x5a, 0xb7, 0xc4, 0x60,
	0x37, 0xa8, 0xb2, 0x81, 0xcd, 0xc3, 0xbe, 0xf3, 0xfa, 0xd5, 0x03, 0x1e, 0x87, 0x5d, 0x4e, 0x51,
	0x53, 0xa9, 0xb8, 0xe6, 0x79, 0xed, 0x43, 0x9a, 0x47, 0xee, 0x11, 0x40, 0xad, 0x0d, 0x9d, 0xd2,
	0x74, 0x12, 0x51, 0x8d, 0xa4, 0x48, 0xbf, 0x1d, 0x9c, 0x94, 0x1f, 0xbe, 0x99, 0xa2, 0xc7, 0x4b,
	0x85, 0x37, 0x21, 0x02, 0xaa, 0x91, 0x94, 0x6a, 0xac, 0x9d, 0x56, 0x4d, 0x27, 0x4f, 0x19, 0x49,
	0xa8, 0x02, 0x9f, 0x03, 0xdf, 0xf3, 0xd3, 0x49, 0xff, 0xc4, 0xba, 0xda, 0x81, 0xad, 0x48, 0x59,
	0x78, 0x47, 0x04, 0xf3, 0x6d, 0xaa, 0x46, 0x37, 0xeb, 0x9a, 0xaa, 0x6c, 0x93, 0x89, 0xa2, 0xa9,
	0xe2, 0xc1, 0xe1, 0xe3, 0x1d, 0xac, 0x1a, 0x2f, 0x1a, 0x4b, 0x35, 0x6e, 0x1b, 0x29, 0xcd, 0x8a,
	0x72, 0x98, 0xa2, 0x15, 0xc5, 0x72, 0xcb, 0x61, 0x21, 0xe5, 0xd2, 0x82, 0x69, 0x50, 0xe9, 0xb4,
	0x1a, 0xe2, 0xe9, 0xdd, 0xbf, 0x74, 0x4e, 0x74, 0xf2, 0x39, 0x3d, 0x87, 0xe4, 0xb3, 0xfb, 0x0d,
	0xb8, 0x5b, 0x00, 0x15, 0x44, 0x49, 0x62, 0xcd, 0x20, 0xe2, 0xfd, 0x07, 0x0d, 0xcc, 0x2c, 0xa1,
	0xb1, 0x98, 0xa5, 0x9d, 0x0b, 0x31, 0x73, 0x2c, 0xa1, 0x68, 0x51, 0xb1, 0x64, 0x2c, 0x50, 0xc9,
	0x46, 0xf7, 0x5f, 0x2a, 0x07, 0x3e, 0xbb, 0x9a, 0xc2, 0x9d, 0x02, 0xa8, 0x62, 0x2d, 0x25, 0xd6,
	0x75, 0x4d, 0x4f, 0x8b, 0xf7, 0xfa, 0x8f, 0x5f, 0xf6, 0xc8, 0x94, 0xd5, 0x14, 0xad, 0x2c, 0xb5,
	0xf8, 0xf2, 0x7e, 0x92, 0xe3, 0x48, 0xc0, 0xbc, 0x59, 0xc5, 0xd6, 0xe6, 0x84, 0x51, 0xcd, 0x38,
	0x28, 0x6a, 0x24, 0xd5, 0x45, 0xd2, 0xe2, 0xed, 0x9b, 0x57, 0x56, 0xe4, 0xe7, 0xf0, 0x24, 0x45,
	0xab, 0xc6, 0xc7, 0x41, 0x51, 0x03, 0x26, 0x0e, 0x27, 0xd1, 0xa2, 0xb6, 0x76, 0x91, 0x34, 0x7c,
	0x49, 0x00, 0x93, 0x19, 0x09, 0xcd, 0x20, 0x9c, 0xc5, 0xf0, 0xa9, 0x2b, 0xa7, 0x3d, 0x4c, 0xd1,
	0x42, 0xd1, 0x13, 0xe3, 0xa3, 0xa1, 0x19, 0x84, 0xf3, 0x60, 0x1e, 0xd8, 0x60, 0x10, 0x46, 0xa4,
	0x57, 0x00, 0x35, 0x8c, 0x88, 0xde, 0x6d, 0x3b, 0xe5, 0xdc, 0x91, 0x63, 0x4d, 0xf9, 0x89, 0xac,
	0xa1, 0x68, 0xf5, 0xf8, 0x88, 0xe8, 0xdd, 0xb6, 0x5b, 0x98, 0x1f, 0xa4, 0x6e, 0xcb, 0x31, 0x0e,
	0x15, 0xe2, 0x50, 0xe9, 0x1d, 0xfa, 0x3a, 0xf8, 0x67, 0x52, 0x21, 0x23, 0xa9, 0xb4, 0xdb, 0x54,
	0xfa, 0x04, 0x30, 0x95, 0x51, 0x31, 0xd4, 0x2e, 0x55, 0xdb, 0xaa, 0xda, 0x7c, 0x4e, 0xbc, 0x71,
	0xa8, 0x36, 0x3f, 0x9f, 0x0d, 0x14, 0xad, 0x1b, 0x1f, 0x1f, 0x0b, 0xce, 0x26, 0xf5, 0x37, 0x73,
	0xb3, 0x83, 0xef, 0x71, 0x66, 0xfe, 0xb3, 0x02, 0xa8, 0x74, 0x7a, 0x6e, 0xd8, 0xee, 0x7e, 0xb1,
	0x9b, 0xd1, 0x53, 0x19, 0x5e, 0x48, 0x51, 0xe3, 0xd8, 0x49, 0x8c, 0xfa, 0xe2, 0x7e, 0xc6, 0x99,
	0x12, 0xfe, 0xc2, 0x0e, 0xbb, 0x72, 0x22, 0x1a, 0x2b, 0xa7, 0xe3, 0xbf, 0x50, 0x66, 0x37, 0xd3,
	0x2f, 0xb8, 0xe6, 0xdb, 0xef, 0xfa, 0xbf, 0x59, 0x53, 0xd2, 0x78, 0x5b, 0x60, 0xec, 0x70, 0xf5,
	0x27, 0x5e, 0xd3, 0xed, 0xbb, 0x9f, 0x1e, 0xed, 0x2d, 0xb5, 0x95, 0x2f, 0x30, 0x60, 0x73, 0x06,
	0xa3, 0x4d, 0xb7, 0x1b, 0xad, 0xe9, 0xf6, 0x7c, 0xcf, 0x99, 0xe9, 0x5e, 0x2f, 0x85, 0xb9, 0x14,
	0xcd, 0x2a, 0x08, 0xe0, 0x1a, 0x6e, 0x53, 0xb9, 0xc3, 0xed, 0xfe, 0x57, 0x7f, 0xde, 0xe7, 0xd9,
	0x0a, 0x2d, 0xa0, 0x28, 0x58, 0x10, 0xa1, 0xb8, 0xd9, 0xf6, 0xc4, 0xc0, 0xd0, 0x87, 0x1e, 0xf5,
	0xac, 0x91, 0xa2, 0xfa, 0xb1, 0x22, 0xe6, 0x9d, 0x6d, 0x07, 0x04, 0x50, 0xed, 0xfe, 0xe6, 0x05,
	0x17, 0x5a, 0x16, 0xe5, 0xa9, 0x50, 0x47, 0xd1, 0x0c, 0x0f, 0x0c, 0x97, 0xc5, 0xda, 0xdc, 0x79,
	0xc4, 0x83, 0xfe, 0xd1, 0x92, 0x82, 0xde, 0xfd, 0x59, 0x4d, 0xb1, 0xe3, 0x7c, 0x94, 0x4f, 0x89,
	0xb7, 0x6e, 0xef, 0xf8, 0xd1, 0xc3, 0x3a, 0xff, 0xa1, 0xe8, 0x9f, 0xae, 0xaf, 0x93, 0x85, 0x0c,
	0xd1, 0x59, 0xce, 0x3e, 0xea, 0x36, 0xfe, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x07, 0x50, 0x41, 0x51,
	0xf8, 0x16, 0x00, 0x00,
}
