// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openconfig/hercules/proto/openconfig/hercules/hercules.proto

package openconfig_hercules

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/openconfig/ygot/proto/yext"
import _ "github.com/openconfig/ygot/proto/ywrapper"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hercules struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hercules) Reset()         { *m = Hercules{} }
func (m *Hercules) String() string { return proto.CompactTextString(m) }
func (*Hercules) ProtoMessage()    {}
func (*Hercules) Descriptor() ([]byte, []int) {
	return fileDescriptor_hercules_c956f2dddb3bdc97, []int{0}
}
func (m *Hercules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hercules.Unmarshal(m, b)
}
func (m *Hercules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hercules.Marshal(b, m, deterministic)
}
func (dst *Hercules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hercules.Merge(dst, src)
}
func (m *Hercules) XXX_Size() int {
	return xxx_messageInfo_Hercules.Size(m)
}
func (m *Hercules) XXX_DiscardUnknown() {
	xxx_messageInfo_Hercules.DiscardUnknown(m)
}

var xxx_messageInfo_Hercules proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Hercules)(nil), "openconfig.hercules.Hercules")
}

func init() {
	proto.RegisterFile("github.com/openconfig/hercules/proto/openconfig/hercules/hercules.proto", fileDescriptor_hercules_c956f2dddb3bdc97)
}

var fileDescriptor_hercules_c956f2dddb3bdc97 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0x4f, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x2f, 0x48, 0xcd, 0x4b, 0xce, 0xcf, 0x4b, 0xcb,
	0x4c, 0xd7, 0xcf, 0x48, 0x2d, 0x4a, 0x2e, 0xcd, 0x49, 0x2d, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9,
	0xc7, 0x2a, 0x03, 0x63, 0xe8, 0x81, 0x95, 0x08, 0x09, 0x23, 0xd4, 0xe8, 0xc1, 0xa4, 0xa4, 0x2c,
	0xb0, 0x9b, 0x5e, 0x99, 0x9e, 0x5f, 0x02, 0x35, 0xb9, 0xb2, 0xbc, 0x28, 0xb1, 0xa0, 0x20, 0xb5,
	0x08, 0xce, 0x80, 0x18, 0x27, 0x65, 0x40, 0x58, 0x67, 0x6a, 0x45, 0x09, 0x98, 0x80, 0xe8, 0x50,
	0xe2, 0xe2, 0xe2, 0xf0, 0x80, 0xda, 0x9b, 0xc4, 0x06, 0x16, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x96, 0xbe, 0x4a, 0x7e, 0xde, 0x00, 0x00, 0x00,
}
